from typing import NoReturn, Tuple, Union


class __parser_iterator:
    def __iter__(self) -> __parser_iterator: ...

    def __next__(self) -> __parser_match: ...

    def __del__(self) -> NoReturn: ...

    @property
    def _source(self) -> str: ...


class __parser_match:
    def __del__(self) -> NoReturn: ...

    def __repr__(self) -> str: ...

    @property
    def value(self) -> str: ...

    @property
    def start(self) -> int: ...

    @property
    def end(self) -> int: ...

    @property
    def type(self) -> int: ...


def parse(source: str, /) -> __parser_iterator: ...


RAW: int = ...
BLOCK: int = ...
INLINE: int = ...
BLOCK3: int = ...
INLINE3: int = ...
BLOCK2: int = ...
INLINE2: int = ...
BLOCK1: int = ...
INLINE1: int = ...


def align(source: str, /) -> str: ...


class __page_code:
    def __del__(self) -> NoReturn: ...

    def __repr__(self) -> str: ...

    def __iter__(self) -> __page_code_iterator: ...


__CODE_TYPE = type(compile("1", "<>", "eval"))


class __page_code_iterator:
    def __del__(self) -> NoReturn: ...

    def __repr__(self) -> str: ...

    def __iter__(self) -> __page_code_iterator: ...

    def __next__(self) -> Tuple[int, Union[str, __CODE_TYPE]]: ...


def compile(source: str, /, name: str, *, optimize: int = ...) -> __page_code: ...


TEXT: int = ...
EVAL: int = ...
EXEC: int = ...
