from typing import NoReturn


class __parser_iterator:
    def __iter__(self) -> __parser_iterator: ...

    def __next__(self) -> __parser_match: ...

    def __del__(self) -> NoReturn: ...

    @property
    def _source(self) -> str: ...


class __parser_match:
    def __del__(self) -> NoReturn: ...

    def __repr__(self) -> str: ...

    @property
    def value(self) -> str: ...

    @property
    def start(self) -> int: ...

    @property
    def end(self) -> int: ...

    @property
    def type(self) -> int: ...


def parse(source, /) -> __parser_iterator: ...


RAW: int = ...
BLOCK: int = ...
INLINE: int = ...
BLOCK3: int = ...
INLINE3: int = ...
BLOCK2: int = ...
INLINE2: int = ...
BLOCK1: int = ...
INLINE1: int = ...
