name: Python package

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ARM64, macos-latest, macOS-M1, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Build wheel
        run: |
          python setup.py bdist_wheel
      - name: Store wheel
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: dist
